### ISSUE TITLE
Malformed Packet, cannot be picked up by remote ID scanner app

### ISSUE THREAD

**Issue by planewave** [cyber-defence-campus/droneRemoteIDSpoofer#2]
I tried to pick up the spoofed signals using OpenDroneID and Drone Scanner, both not working (they are working with real remote IDs from DJI drones)

so I use wireshark to take captures of the beacon packet sented, and found it is a mallformed packet. I believe that is the reason the packets are discarded.
![image](https://github.com/cyber-defence-campus/droneRemoteIDSpoofer/assets/10617156/c517ed43-0f8a-497a-bcb4-ee035e020ee2)
[remoteID_spoof_drones.zip](https://github.com/cyber-defence-campus/droneRemoteIDSpoofer/files/14517293/remoteID_spoof_drones.zip)

**Comment by llorencroma** [comment]
After all, only a minimal Beacon packet is generated, so probably it's missing some of the header fields that Wireshark tries to parse. I will try to work on that

**Comment by planewave** [comment]
I found a fix, it is due to the wrong length of the tag. it can be fixed like this

```
    ie_vendor_parrot = scapy.Dot11EltVendorSpecific(
        ID=221, len=len(vendor_spec_data) + 3, oui=16387004, info=vendor_spec_data
    )
```

but I think my real issue is not here. How can I set up the wifi protocol being used? By default, it used 802.11b, but I found that DJI uses 802.11g. also, can I set up the wifi channel too?
I was reading scapy document, but it is like Arabic to me.

Thank you

**Comment by llorencroma** [comment]
Good that you found the fix. Regarding the channel, a generic example would be the following:

```
def generate_beacon_frame(ssid, ap_mac, channel):
    dot11 = Dot11(type=0, subtype=8, addr1="ff:ff:ff:ff:ff:ff",
                  addr2=ap_mac, addr3=ap_mac)
    beacon = Dot11Beacon(cap="ESS+privacy")
    essid = Dot11Elt(ID="SSID", info=ssid, len=len(ssid))
    channel = Dot11Elt(ID="DSset", info=chr(channel))
    frame = RadioTap()/dot11/beacon/essid/channel
    return frame

channel = 6  # Change this to your desired channel

# Create a packet and send it in a loop to beacon on the specified channel
beacon_frame = generate_beacon_frame("your_ssid", ap_mac_address, channel)
sendp(beacon_frame, iface="wlan0", inter=0.1, loop=True)
    
```
   
For the specific case of this spoofer, you should add a new Dot11Elt. Try this (just above line 186):
```
channel = 6 ## here you use the channel number you want
ie_channel = Dot11Elt(ID="DSset", info=chr(channel))
return scapy.RadioTap() / scapy.Dot11(type=0, subtype=8, addr1=dest_addr, addr2=src_addr,
                                          addr3=src_addr) / scapy.Dot11Beacon() / ie_ssid / ie_channel / ie_vendor_parrot

```
Let me know if that works. Then we could add it as an argument for the script.

**Comment by planewave** [comment]
and how about the protocol? Do you have any idea how to enable 802.11g only? or maybe use the `iw` command?

**Comment by llorencroma** [comment]
I would say that this needs to be solved with `iw`. Make sure your wireless adapter supports 802.11g.
